const API='https://fixy-calendar-462657202516.southamerica-east1.run.app';
const services=[
 {id:'diagnostico',title:'Diagnóstico logístico',detail:'Revisamos tu operación y detectamos el mejor punto de partida.',duration:20},
 {id:'fulfillment',title:'FixyFull',detail:'Stock, preparación y despacho para tu e-commerce.',duration:15},
 {id:'envios',title:'Envíos y distribución',detail:'Same Day, Next Day, Flex e interior.',duration:15}
];
const advisors={gonzalo:{id:'gonzalo',name:'Gonzalo Jácome',role:'Ejecutivo de cuentas',image:'assets/gonzalo.webp?v=2'},micaela:{id:'micaela',name:'Micaela Pucheta',role:'Ejecutiva de cuentas',image:'assets/micaela.webp?v=2'}};
function businessDays(){const out=[],d=new Date();while(out.length<4){if(![0,6].includes(d.getDay()))out.push(new Date(d));d.setDate(d.getDate()+1)}return out}
function iso(d){return new Intl.DateTimeFormat('en-CA',{timeZone:'America/Argentina/Buenos_Aires'}).format(d)}
const dates=businessDays();
let state={step:1,service:'diagnostico',date:iso(dates[0]),slot:null,advisor:'',slots:[],loading:false,error:'',result:null,showAllTimes:false};
const panel=document.querySelector('#panel');
const selectedService=()=>services.find(x=>x.id===state.service);
function progress(){document.querySelectorAll('.progress-row span').forEach((el,i)=>el.classList.toggle('active',i<state.step))}
async function loadSlots(){state.loading=true;state.error='';state.slot=null;state.showAllTimes=false;render();try{const r=await fetch(`${API}/availability?date=${state.date}&duration=${selectedService().duration}`);if(!r.ok)throw 0;state.slots=(await r.json()).slots||[]}catch{state.error='No pudimos consultar los calendarios. Probá nuevamente.'}finally{state.loading=false;render()}}
function go(n){state.step=n;if(n===2)loadSlots();else render();scrollTo({top:0,behavior:'smooth'})}
function serviceCard(x){return `<button class="service ${state.service===x.id?'selected':''}" data-service="${x.id}"><span class="radio"></span><span><strong>${x.title}</strong><small>${x.detail}</small></span><b>${x.duration} min</b></button>`}
function advisorCard(id){const x=advisors[id];return `<button class="advisor ${state.advisor===id?'selected':''}" data-advisor="${id}"><img src="${x.image}" alt="${x.name}"><span><strong>${x.name}</strong><small>${x.role}</small></span><span class="radio"></span></button>`}
function timeGroups(){return [{label:'Mañana',slots:state.slots.filter(x=>Number(x.time.slice(0,2))<13)},{label:'Tarde',slots:state.slots.filter(x=>Number(x.time.slice(0,2))>=13)}].filter(x=>x.slots.length)}
function groupedTimes(){const groups=timeGroups();const hidden=groups.some(group=>group.slots.length>3);return `<div class="time-groups">${groups.map(group=>`<section class="time-group"><h3>${group.label}</h3><div class="times">${(state.showAllTimes?group.slots:group.slots.slice(0,3)).map(x=>`<button class="${state.slot?.start===x.start?'selected':''}" data-start="${x.start}">${x.time}</button>`).join('')}</div></section>`).join('')}${hidden?`<button class="show-times" data-expand>${state.showAllTimes?'Ver menos horarios':'Ver todos los horarios'}</button>`:''}</div>`}
function render(){progress();const service=selectedService();
 if(state.result){const confirmedAdvisor=advisors[state.advisor];const confirmedDate=new Date(state.slot.start);panel.innerHTML=`<div class="success"><div class="success-icon">✓</div><span class="eyebrow">REUNIÓN CONFIRMADA</span><h2>¡Tu reunión quedó agendada!</h2><p>La invitación de Google Calendar con el Meet fue enviada por email.</p><div class="confirmed-advisor"><img src="${confirmedAdvisor.image}" alt="${confirmedAdvisor.name}"><span><small>Tu ejecutivo</small><strong>${confirmedAdvisor.name}</strong></span></div><div class="summary details"><div><span>Servicio</span><strong>${service.title}</strong></div><div><span>Fecha</span><strong>${confirmedDate.toLocaleDateString('es-AR',{weekday:'long',day:'numeric',month:'long'})}</strong></div><div><span>Horario</span><strong>${confirmedDate.toLocaleTimeString('es-AR',{hour:'2-digit',minute:'2-digit'})}</strong></div><div><span>Duración</span><strong>${service.duration} minutos</strong></div></div>${state.result.meetLink?`<a class="primary" href="${state.result.meetLink}">Abrir Google Meet</a>`:''}</div>`;return}
 if(state.step===1)panel.innerHTML=`<div class="panel"><span class="step-label">PASO 1 DE 4</span><h2>¿Sobre qué querés conversar?</h2><p class="sub">Seleccioná el punto de partida.</p><div class="option-list">${services.map(serviceCard).join('')}</div><button class="primary" data-next="2">Elegir día y horario →</button></div>`;
 if(state.step===2)panel.innerHTML=`<div class="panel"><button class="back" data-next="1">← Volver</button><span class="step-label">PASO 2 DE 4</span><h2>Elegí cuándo te queda mejor</h2><p class="sub">Disponibilidad real · Horario de Buenos Aires.</p><div class="dates">${dates.map(d=>`<button class="${state.date===iso(d)?'selected':''}" data-date="${iso(d)}"><small>${d.toLocaleDateString('es-AR',{weekday:'short'}).toUpperCase()}</small><strong>${d.getDate()}</strong><span>${d.toLocaleDateString('es-AR',{month:'short'}).toUpperCase()}</span></button>`).join('')}</div>${state.loading?'<p>Cargando horarios…</p>':groupedTimes()}${state.error?`<p class="sub">${state.error}</p>`:''}<button class="primary" ${state.slot?'':'disabled'} data-next="3">Ver ejecutivos disponibles →</button></div>`;
 if(state.step===3)panel.innerHTML=`<div class="panel"><button class="back" data-next="2">← Cambiar horario</button><span class="step-label">PASO 3 DE 4</span><h2>¿Con quién querés conversar?</h2><p class="sub">Estas personas están libres en el horario seleccionado.</p><div class="advisor-grid">${state.slot.advisors.map(advisorCard).join('')}</div><button class="primary" ${state.advisor?'':'disabled'} data-next="4">Completar mis datos →</button></div>`;
 if(state.step===4)panel.innerHTML=`<div class="panel"><button class="back" data-next="3">← Cambiar ejecutivo</button><span class="step-label">PASO 4 DE 4</span><h2>¿Cómo te contactamos?</h2><p class="sub">Al confirmar crearemos la reunión de Google Meet.</p><form id="booking-form"><label>Nombre y apellido<input name="name" required></label><label>Empresa<input name="company" required></label><label>WhatsApp<input name="whatsapp" required></label><label>Email<input name="email" type="email" required></label><div class="mini-summary"><span>${service.title}</span><strong>${new Date(state.slot.start).toLocaleString('es-AR')}</strong><span>${advisors[state.advisor].name}</span></div>${state.error?`<p class="sub">${state.error}</p>`:''}<button class="primary" ${state.loading?'disabled':''}>${state.loading?'Confirmando…':'Confirmar reunión →'}</button></form></div>`;
 panel.querySelectorAll('[data-service]').forEach(b=>b.onclick=()=>{state.service=b.dataset.service;render()});
 panel.querySelectorAll('[data-date]').forEach(b=>b.onclick=()=>{state.date=b.dataset.date;loadSlots()});
 panel.querySelectorAll('[data-start]').forEach(b=>b.onclick=()=>{state.slot=state.slots.find(x=>x.start===b.dataset.start);state.advisor='';render()});
 panel.querySelectorAll('[data-expand]').forEach(b=>b.onclick=()=>{state.showAllTimes=!state.showAllTimes;render()});
 panel.querySelectorAll('[data-advisor]').forEach(b=>b.onclick=()=>{state.advisor=b.dataset.advisor;render()});
 panel.querySelectorAll('[data-next]').forEach(b=>b.onclick=()=>!b.disabled&&go(Number(b.dataset.next)));
 const form=panel.querySelector('#booking-form');if(form)form.onsubmit=book;
}
async function book(e){e.preventDefault();state.loading=true;state.error='';render();const f=new FormData(e.target);try{const r=await fetch(`${API}/book`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({advisor:state.advisor,start:state.slot.start,duration:selectedService().duration,service:selectedService().title,name:f.get('name'),company:f.get('company'),whatsapp:f.get('whatsapp'),email:f.get('email')})});const data=await r.json();if(!r.ok)throw new Error(data.error);state.result=data;if(window.dataLayer)window.dataLayer.push({event:'booking_confirmed',service:'reservas',cta_location:'reservas',value:selectedService().title,fixy_page:'reservas'});if(window.gtag)gtag('event','booking_confirmed',{value:selectedService().title,fixy_page:'reservas'});if(window.fbq)fbq('track','Schedule',{content_name:selectedService().title})}catch(err){state.error=err.message||'No pudimos confirmar la reunión.'}finally{state.loading=false;render()}}
render();
